# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.udaconnect.proto.connection_data_pb2 as connection__data__pb2


class ConnectionDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindContacts = channel.unary_unary(
                '/ConnectionDataService/FindContacts',
                request_serializer=connection__data__pb2.SearchMessage.SerializeToString,
                response_deserializer=connection__data__pb2.ConnectionMessageList.FromString,
                )


class ConnectionDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindContacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectionDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.FindContacts,
                    request_deserializer=connection__data__pb2.SearchMessage.FromString,
                    response_serializer=connection__data__pb2.ConnectionMessageList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ConnectionDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConnectionDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ConnectionDataService/FindContacts',
            connection__data__pb2.SearchMessage.SerializeToString,
            connection__data__pb2.ConnectionMessageList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
